services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=auth-db
      - DB_PORT=3306
      - DB_NAME=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - auth-db

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
    - SPRING_PROFILES_ACTIVE=docker
    - DB_HOST=notification-db
    - DB_PORT=3306
    - DB_NAME=notification_db
    - DB_USERNAME=root
    - DB_PASSWORD=root
    - SPRING_MAIL_HOST=smtp.gmail.com
    - SPRING_MAIL_PORT=587
    - SPRING_MAIL_USERNAME=${MAIL_USER}
    - SPRING_MAIL_PASSWORD=${MAIL_PASS}
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
    - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    - APP_MAIL_FROM=${MAIL_USER}
    depends_on:
      - notification-db

  auth-db:
    image: mysql:8
    container_name: auth-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_db
    ports:
      - "3307:3306"

  notification-db:
    image: mysql:8
    container_name: notification-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notification_db
    ports:
      - "3308:3306"
